services:
  foopbot:
    image: foopbot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs